apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-cron-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-cron
  template:
    metadata:
      labels:
        app: django-cron
    spec:
      containers:
      - name: django
        image: django-cron-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
